# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 671))
        self.tabWidget.setStyleSheet("QTabBar::tab { height: 30;width: 430px; }")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.input_text = QtWidgets.QPlainTextEdit(self.tab)
        self.input_text.setGeometry(QtCore.QRect(0, 60, 411, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.output_text = QtWidgets.QPlainTextEdit(self.tab)
        self.output_text.setGeometry(QtCore.QRect(440, 60, 411, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.output_text.setFont(font)
        self.output_text.setObjectName("output_text")
        self.save_btn = QtWidgets.QPushButton(self.tab)
        self.save_btn.setGeometry(QtCore.QRect(670, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.open_btn = QtWidgets.QPushButton(self.tab)
        self.open_btn.setGeometry(QtCore.QRect(670, 580, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.open_btn.setFont(font)
        self.open_btn.setObjectName("open_btn")
        self.run_btn = QtWidgets.QPushButton(self.tab)
        self.run_btn.setGeometry(QtCore.QRect(350, 580, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.clear_btn = QtWidgets.QPushButton(self.tab)
        self.clear_btn.setGeometry(QtCore.QRect(10, 580, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.msg_text = QtWidgets.QPlainTextEdit(self.tab)
        self.msg_text.setGeometry(QtCore.QRect(0, 490, 851, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.msg_text.setFont(font)
        self.msg_text.setObjectName("msg_text")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName("tab_2")
        self.graph_area = QtWidgets.QLabel(self.tab_2)
        self.graph_area.setGeometry(QtCore.QRect(10, 10, 831, 511))
        self.graph_area.setText("")
        self.graph_area.setObjectName("graph_area")
        self.msg_2_text = QtWidgets.QPlainTextEdit(self.tab_2)
        self.msg_2_text.setGeometry(QtCore.QRect(0, 540, 851, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.msg_2_text.setFont(font)
        self.msg_2_text.setObjectName("msg_2_text")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TINY Language Compiler"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Input TINY language code here and hit run!"))
        self.open_btn.setText(_translate("MainWindow", "Open"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Compiler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Syntax Tree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
